#!/bin/bash

root_dir='/home/bridge/ggdjl/ipcc_ar6/ts_ssp/ssp_mod/CMIP6_BRIDGE'
gridfile='/home/bridge/ggdjl/ipcc_ar6/ts_ssp/ssp_mod/tas_annual_longterm_grid.nc'

gen_files=0
gen_diffs=0
gen_ens=1

modlist='CanESM5 IPSL-CM6A-LR MRI-ESM2-0'
ssplist='ssp126 ssp585'
yearlist='2300 2100'

if [ ${gen_files} -eq 1 ] ; then


for model in ${modlist} ; do

fileyears_2300_ssp126='210101-230012'
fileyears_2100_ssp126='201501-210012'
extyears_2300_ssp126='2161/2400'   # last 20 years
extyears_2100_ssp126='793/1032'    # last 20 years

fileyears_2300_ssp585='210101-230012'
fileyears_2100_ssp585='201501-210012'
extyears_2300_ssp585='2161/2400'   # last 20 years
extyears_2100_ssp585='793/1032'    # last 20 years

fileyears_1850_historical='185001-201412'
fileyears_1995_historical='185001-201412'
extyears_1850_historical='1/612'       # first 51 years
extyears_1995_historical='1741/1980'   # last 20 years

grid='gr'

if [ ${model} == 'IPSL-CM6A-LR' ] ; then
echo ${model}
echo 'no change to defaults'
fi

if [ ${model} == 'MRI-ESM2-0' ] ; then
echo ${model}
grid='gn'
fi

if [ ${model} == 'CanESM5' ] ; then
echo ${model}
grid='gn'
fileyears_2300_ssp585='218101-230012'
extyears_2300_ssp585='1201/1440'   # last 20 years
fi

for ssp in ${ssplist} ; do
for year in ${yearlist} ; do

echo ${ssp} 
echo ${year}

fileyear=fileyears_${year}_${ssp}
filein=${root_dir}/${model}/tas_Amon_${model}_${ssp}_r1i1p1f1_${grid}_${!fileyear}.nc
fileout=${root_dir}/${model}/tas_${ssp}_${year}.nc

extyear=extyears_${year}_${ssp}

echo ${filein}
echo ${!extyear}

cdo -O seltimestep,${!extyear} ${filein} tmp.nc
cdo -O timmean tmp.nc ${fileout}

echo ''

\rm -f tmp.nc
done
done

for ssp in historical ; do
for year in 1850 1995 ; do

fileyear=fileyears_${year}_${ssp}
filein=${root_dir}/${model}/tas_Amon_${model}_${ssp}_r1i1p1f1_${grid}_${!fileyear}.nc
fileout=${root_dir}/${model}/tas_${ssp}_${year}.nc

extyear=extyears_${year}_${ssp}

echo ${filein}
echo ${!extyear}

cdo -O seltimestep,${!extyear} ${filein} tmp.nc
cdo -O timmean tmp.nc ${fileout}

\rm -f tmp.nc

echo ''

done
done


done


fi


if [ ${gen_diffs} -eq 1 ] ; then

for mod in ${modlist} ; do
for ssp in ${ssplist} ; do
for year in ${yearlist} ; do
for base in 1850 1995 ; do

cdo -O sub ${mod}/tas_${ssp}_${year}.nc ${mod}/tas_historical_${base}.nc ${mod}/tas_${ssp}_${year}-historical_${base}.nc

cdo -O remapbil,r360x180 -selname,tas ${mod}/tas_${ssp}_${year}-historical_${base}.nc ${mod}/tas_${ssp}_${year}-historical_${base}_regrid.nc

done
done
done
done

fi


if [ ${gen_ens} -eq 1 ] ; then

for ssp in ${ssplist} ; do
for year in ${yearlist} ; do
for base in 1850 1995 ; do

filelist=''
for mod in ${modlist} ; do
filelist=${filelist}"${mod}/tas_${ssp}_${year}-historical_${base}_regrid.nc "
done

cdo ensmean ${filelist} ensmean_tas_${ssp}_${year}-historical_${base}_regrid.nc 

done
done
done

fi

exit
